services:
  - type: web
    name: weather-bot-final
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
    
      - key: OPENWEATHER_TOKEN
        sync: false
    
      - key: OWNER_ID
        sync: false
      
    
   
